### ISSUE TITLE
Nodemon 

### ISSUE THREAD

**Issue by DeepakTDK** [iamshaunjp/node-crash-course#13]
Nodemon is updating and auto refreshing only the server and those changes are not changed in the browser. so that we have to restart the server everytime. i don't know how your browser is updating the changes automatically.

**Comment by demha8444** [comment]
I know of an extension in VS Code that helps with that, maybe he is using that

**Comment by JamesMalarkey** [comment]
Just type "nodemon app.js".

**Comment by DeepakTDK** [comment]
@JamesMalarkey Yeah i found the solution for that. i think i used "npm run app.js".
