### ISSUE TITLE
Code not in the repo

### ISSUE THREAD

**Issue by TarikSeyceri** [iamshaunjp/node-crash-course#24]
Hello sir, i followed your video: https://www.youtube.com/watch?v=zW_tZR0Ir3Q&ab_channel=TheNetNinja

Really nice one

I would like to get the code, but it seems it doesn't exist, i liked the structure, and i am a lazy developer, i would want your code to be a boilerplate for a project that i am planning.

Thank you..

**Comment by undevable** [comment]
Hey @TarikSeyceri. The code does exist, but there are in different branches, based on the lesson. To navigate through the branches, click on the drop-down menu that says, "master", with a git branch icon next to it.

**Comment by TarikSeyceri** [comment]
Thanks a lot sir, so i have to pick the last lesson branch to get the final code, usually master branch is the final code, so i got confused, anyway, thank you :)
